/hik_camera:
  ros__parameters:
    camera_name: narrow_stereo

    exposure_time: 6000.0
    gain: 15.0
    rotation_angle: 2
    # Valid values: 0=None, 1=90deg, 2=180deg, 3=270deg
    publish_compressed: true
    jpeg_quality: 60

/webrtc_stream_server:
  ros__parameters:
    bind_address: 0.0.0.0
    port: 8554
    base_path: /webrtc
    input_topic: /image_raw/compressed
    fps: 30
    stun_server: ""

